name: 🚀Befly API Gateway CI

on:
  pull_request:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gateway Repository
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.PAT }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Git authentication for submodules
        run: |
          git config --global url."https://${{ secrets.PAT }}@github.com".insteadOf "https://github.com"
          git submodule update --init --recursive

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew 
          ./gradlew clean build -x test

      - name: Get Git short SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile.prod -t ${{ secrets.DOCKER_USERNAME }}/befly-gateway:${{ steps.vars.outputs.sha }} .

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/befly-gateway:${{ steps.vars.outputs.sha }}
