name: 🚀Befly API Gateway CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gateway Repository
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.PAT }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Git authentication for submodules
        run: |
          git config --global url."https://${{ secrets.PAT }}@github.com".insteadOf "https://github.com"
          git submodule update --init --recursive

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew 
          ./gradlew clean build -x test