name: 🚀Befly API Gateway CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gateway Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: make application.yml
        run: |
          cd ./src/main
          mkdir -p resources
          cd resources
            
          touch ./application.yml
          echo "${{ secrets.APPLICATION_YML }}" >> ./application.yml

      - name: make application-dev.yml
        run: |
          cd ./src/main
          cd ./resources
            
          touch ./application-dev.yml
          echo "${{ secrets.APPLICATION_DEV_YML }}" >> ./application-dev.yml

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew 
          ./gradlew clean build -x test