name: 🚀Befly API Gateway CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gateway Repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: make application.yml
        run: |
          git submodule update --init --recursive
          cp ./config/gateway-service/application.yml ./src/main/resources/application.yml
          cp ./config/gateway-service/application-dev.yml ./src/main/resources/application-dev.yml

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew 
          ./gradlew clean build -x test